source 'https://rubygems.org'

ruby '2.2.0'

gem 'rails', '~> 4.2.0'

# Assets
gem 'sass', '~> 3.4.11'
gem 'sass-rails', '5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'pg', '0.17.1'
gem 'jquery-rails', '4.0.3'
gem 'jquery-ui-rails', '5.0.3'
gem 'devise', '3.4.1'
gem 'bootstrap-sass', '3.3.3'
gem 'will_paginate-bootstrap', '1.0.1'
gem 'figaro', '1.1.0'
gem 'httparty', '0.13.3'

gem 'sdoc', '~> 0.4.0', group: :doc

# Application Server
gem 'unicorn', '4.8.3'

group :development, :test do
  gem 'rspec-rails', '3.1.0'
  gem 'guard-rspec', '~> 4.5.0'
  gem 'factory_girl_rails', '4.5.0'
  gem 'capybara', '2.4.4'
  gem 'poltergeist', '1.5.1'
  gem 'pry'
  gem 'pry-remote'
  gem 'quiet_assets'
  gem 'database_cleaner', '~> 1.4.0'
  gem 'unicorn-rails'
end

