#!/bin/bash
set -e

hmac-sha256s(){
 local key="$1"
 local data="$2"

 shift 2
 printf "$data" | openssl dgst -binary -sha256 -hmac "$key" | od -An -vtx1 | sed 's/[ \n]//g' | sed 'N;s/\n//'
}

hmac-sha256h(){
 local key="$1"
 local data="$2"

 shift 2
 printf "$data" | openssl dgst -binary -sha256 -mac hmac -macopt "hexkey:$key" | od -An -vtx1 | sed 's/[ \n]//g' | sed 'N;s/\n//'
}

# $1: secret access key
# $2: request time
# $3: bucket region
# $4: payload hash
aws_s3_signature () {
  local secret_access_key="$1"
  local request_time="$2"
  local bucket_region="$3"
  local payload_hash="$4"

  local aws4secret="AWS4"$secret_access_key
  local request_date=$(printf "${request_time}" | cut -c 1-8)
  local request_service="s3"

  echo $(hmac-sha256h $(hmac-sha256h $(hmac-sha256h $(hmac-sha256h $(hmac-sha256s $aws4secret $request_date ) $bucket_region) $request_service) "aws4_request") $payload_hash)
}

# $1: payload
aws_s3_payload_hash () {
  local payload="$1"

  local payload_hash=$(printf "$payload" | openssl base64 )
  local payload_hash=$(echo -en $payload_hash |  sed "s/ //g")

  echo "$payload_hash"
}

# $1: access key id
# $2: secret access key
# $3: bucket name
# $4: bucket region
# $5: remote file
# $6: local file
upload_to_aws_s3 () {
  local access_key_id="$1"
  local secret_access_key="$2"
  local bucket_name="$3"
  local bucket_region="$4"
  local remote_file="$5"
  local local_file="$6"

  local request_time=$(date +"%Y%m%dT%H%M%SZ")
  local request_service="s3"
  local request_date=$(printf "${request_time}" | cut -c 1-8)
  local algorithm="AWS4-HMAC-SHA256"
  local request_date_plus_3600_seconds=$(date +"%Y-%m-%d %H:%M:3600")
  local expire=$(date --date="$request_date_plus_3600_seconds" +"%Y-%m-%dT%H:%M:%SZ")
  local acl="private"

  local post_policy='{"expiration":"'$expire'","conditions": [{"bucket":"'$bucket_name'" },{"acl":"'$acl'" },["starts-with", "$key", "'$remote_file'"],["eq", "$Content-Type", "application/octet-stream"],{"x-amz-credential":"'$access_key_id'/'$request_date'/'$bucket_region'/'$request_service'/aws4_request"},{"x-amz-algorithm":"'$algorithm'"},{"x-amz-date":"'$request_time'"}]}'

  local payload_hash=$(aws_s3_payload_hash "$post_policy")

  local signature=$(aws_s3_signature "$secret_access_key" "$request_time" "$bucket_region" "$payload_hash")

  curl \
      --silent \
      --limit-rate 900k \
      --connect-timeout 120 \
      -F "key=""$remote_file" \
      -F "acl="$acl"" \
      -F "Content-Type="application/octet-stream"" \
      -F "x-amz-algorithm="$algorithm"" \
      -F "x-amz-credential="$access_key_id/$request_date/$bucket_region/$request_service/aws4_request"" \
      -F "x-amz-date="$request_time"" \
      -F "policy="$payload_hash"" \
      -F "X-Amz-Signature="$signature"" \
      -F "file=@"$local_file http://$bucket_name.s3.amazonaws.com/
}
