#!/bin/bash
set -e

trap "echo exit signal received... exiting;exit" SIGINT SIGTERM SIGKILL

# include dependencies
dir="${BASH_SOURCE%/*}"
if [[ ! -d "$dir" ]]; then dir="$PWD"; fi
. "$dir/redis_helper"
